package problems.problem2;

/**
 * Created by Stefan on 25/10/14.
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */
public class Solution {

    private static int N = 4000000;
    private static int result = 2;

    public static int calculateFibonacciSum(int firstValue, int secondValue)
    {
        if(firstValue + secondValue <= N)
        {
            if((firstValue+secondValue) % 2 == 0) result += firstValue + secondValue;
            calculateFibonacciSum(secondValue, firstValue + secondValue);
        }

        return result;
    }
}
